# Generated by Django 5.1.5 on 2025-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Stationar", "Stationar"),
                            ("Electronics", "Electronics"),
                            ("Groceries", "Groceries"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
