# Generated by Django 5.1.5 on 2025-08-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_order_options_alter_products_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "order"},
        ),
    ]
