# Generated by Django 5.1.5 on 2025-08-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
    ]
