# Generated by Django 5.1.5 on 2025-08-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_products_created_at_products_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
