# Generated by Django 5.2.5 on 2025-08-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="Profile_Images/avatar.jpg", upload_to="Profile_Images"
            ),
        ),
    ]
